electron-userland/electron-prebuilt

package.json
=> Fix a typo

.gitignore, .travis.yml, install.js, package.json, path.txt, test/index.js
Added cache folder in home directory that prevents unnecessary downloads
=> Add cache of zips in home directory

install.js
=> version 0.25.3

install.js
=> update electron shell to 0.26.1

install.js
I've left `package.json` unchanged so you can `npm version patch` for tags / etc.
=> bump to 0.27.3

install.js
Same as https://github.com/mafintosh/electron-prebuilt/pull/38
=> Bump to version 0.28.1

README.md, install.js
Addresses comments in pull request #55.
=> Add target arch support

install.js
=> Add FreeBSD path to install.js

install.js
```shell
export npm_config_platform=mas
npm install
```
=> Allow download builds for MAS

package.json
cc @kevinsawicki who will be coordinating the next release.
For context, see #160
=> change npm package name to `electron`

README.md
typos are annoying ;) here's a quick fix! Cheers.
=> fixes typo within readme

index.js
Fixes #229 
cc @MarshallOfSound @kevinsawicki
=> hardcode module path in installation error message

electron.d.ts, package.json
The Electron project will soon begin publishing a TypeScript declaration file `electron.d.ts` with every release: https://github.com/electron/electron/pull/7857
Many existing third-party `.d.ts` files are published to registries such as [DefinitelyTyped] and [typings], but this is not the ideal approach for publishing, as it requires TypeScript users to manually seek out and install the definitions, and keep them up to date as well.
Because we own the publishing process for the `electron` npm package, we can do our TypeScript users a favor by bundling the file with the package.
To make the Typescript definitions work "out of the box" for users of the `electron` npm package, this PR bundles in that new file and adds a reference to it in `package.json`, per the [typescript guide] …
=> add electron.d.ts for built-in TypeScript support

electron.d.ts
=> Update to electron.d.ts@1.7.0

electron.d.ts
Prep for the upcoming 1.6.10 Electron release.
=> Update to electron.d.ts@1.6.10

electron.d.ts
Typescript file for the upcoming 1.7.1 beta release.
=> Update to electron.d.ts@1.7.1

electron.d.ts
=> Upgrade typescript file to 1.7.2

electron.d.ts
=> Add electron.d.ts@1.7.3

electron.d.ts
Bumps the docs for the upcoming 1.7.4 release.
=> Upgrade .d.ts file to 1.7.4

electron.d.ts
=> update electron.d.ts for 1.6.12
