electron-userland/electron-prebuilt

- install.js
We must pick this up from the repo itself, we could use ` /repos/:owner/:repo/releases/latest` from the github API.
> version 0.25.2

- .gitignore
- .npmignore
- package.json
> updated scripts / .ignores

- install.js
Can't we just use the version directly from `package.json` or am I missing something?
> use version from package.json

- cli.js
**TL;DR: The current `cli.js` wrapper always exits with `0`, no matter what electron actually exits with. This PR fixes that.**
Real-life example: some applications (like electron itself) have an interesting test setup:
* electron is launched, from which
* ...a BrowserWindow is created, in which
* ...some javascript is loaded (e.g. mocha + a bunch of specs)
* The test results (number of tests failed, for instance) are [sent by ipc](https://github.com/atom/electron/blob/399f47ef0f0017a1ad52fab2399b1e1ef5103e29/spec/static/index.html#L73) back to the nodejs side
* ...where [`process.exit()` is called](https://github.com/atom/electron/blob/399f47ef0f0017a1ad52fab2399b1e1ef5103e29/spec/static/main.js#L24) so that test failures result in a non-zero exit code
* which is useful when running on …
> Relay electron exit code

- index.js
- install.js
Allows install to work even if our directory is moved later.
> Don't save __dirname into path.txt.

- install.js
The standard way of specifying whether you want strict-ssl or not
is to add an entry into your npm config file for strict-ssl. Use
that entry (which is passed to the install.js as an environment
variable) to set the option for strictSSL in electron-download.
> Allow specifying StrictSSL in the NPM config file

- install.js
As discussed in both #75 and #91, in particular [this comment](https://github.com/electron-userland/electron-prebuilt/pull/75#issuecomment-191115502). We can not use environment variables to reliably access npm configuration settings, instead we must require in the `npm` module and use its api.
This supercedes other pull requests that were trying to do the same thing.
Fixes #91
Closes #75
> Fix npm usage

- README.md
This will make it easier to see the current published version of `electron-prebuilt`
> Make npm badge link to package page

- CONTRIBUTING.md
- README.md
- issue_template.md
This change updates the readme:
- Fix old repo URLs
- Point to docs on website
- Use `npm install electron`
cc @jlord @kevinsawicki
> Update readme after package rename

- install.js
This pull request tweaks the error message for unsupported platforms to hopefully be a little clearer about the error when a platform build of Electron is unavailable.
It changes it from:
> Unknown platform: n64
to:
> Electron builds are not available on platform: n64
> Mention builds not available when platform not found

- .npmignore
- .travis.yml
- README.md
- appveyor.yml
- install.js
- package.json
I'm updating the version number to force an upgrade.
Also, update Travis to test against Node >= 4 on Linux and OSX.
Oddly enough, I had to upgrade `path-exists` as well, otherwise it wouldn't download correctly.
Fixes #51.
> Upgrade electron-download for checksum support

- install.js
Hi, I think this issue was related: https://github.com/electron-userland/electron-prebuilt/issues/99
I use Electron as a dependency. The path.txt file had the wrong path when I built for Windows on a Mac using `npm install --platform=win32 --arch=ia32 --production`. The path variable was set to what it would be for my OS's platform, not the target platform. 
If the [platform used to determine the path saved to path.exe](https://github.com/electron-userland/electron-prebuilt/blob/master/install.js#L19) matches [the one downloaded](https://github.com/electron-userland/electron-prebuilt/blob/master/install.js#L39), everything works.
Thanks for everything!
> Change platform path to match downloaded one

- .travis.yml
- package.json
Upgrade to an `electron-download` version that includes https://github.com/electron-userland/electron-download/pull/35
Closes #193
> Upgrade electron download to fix Mac CI issue

- install.js
`electron-download` progress should be suppressed for anything but `info`, `verbose` and `silly` npm log levels. 
I don't know if this will be surprising for anyone having a default npm `warn` level, as you wouldn't see the specific progress (and possibly think it's broken), but just having `silent` as the switch to turn off progress is very inconvenient for automated build logs.
What do you guys think?
> Download progress should only show for appropriate log levels

- .gitignore
- .npmignore
- install.js
- test/errors.js
This pull request updates the install sequence to write the `path.txt` file last, after uncompressing has happened. This way it is only written if downloading and extracting both succeed.
This will make it easier to check for errors when launching a possibly corrupted install via #224.
Also adds a few specs for failure cases to guard against regressions.
> Write path.txt file after uncompressing

- index.js
- test/errors.js
This is to handle issues such as https://github.com/electron/electron-quick-start/issues/122 where the install either terminated early or failed for whatever reason.  We can throw a more descriptive error in this case.
> Check that the path file exists before spawning

- README.md
As documented later in the README.md already, plus the download numbers look bigger too.
> Update README.md badge: Drop prebuilt

- install.js
Sometimes there is no access to GitHub on the build machines.
But Electron during the installation downloads released zip file from https://github.com/electron/electron/releases.
Prepared zip files could be stored by the maintainer of the build machine to some local directory.
This fix allows to use the local cache with released zip files during installation of Electron.
> Use process.env.electron_config_cache to get the released zip file from the local directory during installation of Electron.

- electron.d.ts
Updates the file in this repository to 1.6.9, to be released after this gets merged.
Doing this manually to start, being automated in https://github.com/electron/electron-prebuilt-updater/pull/5
Refs https://github.com/electron-userland/electron-prebuilt/pull/209
/cc @zeke
> Update electron.d.ts for 1.6.9

- package.json
This PR adds `@types/node` as a dependency.
Pros
- This will make `npm install electron` take care of adding everything that TypeScript users will need when writing Electron apps.
Cons
- People who don't use TypeScript are needlessly downloading an extra dependency. (Though it is small, inert, and has no dependencies)
- Most TypeScript users [are already accustomed](https://github.com/electron/electron-typescript-definitions/issues/43#issuecomment-300687960) to adding `@types/node` to their projects, and it appears that Visual Studio Code [bundles the node types by default](https://github.com/electron/electron-typescript-definitions/issues/43#issuecomment-300691565).
- It's a scoped package, which has a slightly higher degree of vendor lock-in than a package in the global npm namespace.
I …
> add @types/node

- README.md
- install.js
Downloading from cache causes a checksum check that causes some builds to fail(see https://github.com/electron/electron/issues/8653) that  that rely on stable electron releases(pre electron v1.7.0 beta) where chromedrive is not named based on electron version. This will add the option to always force a redownload.
> added force option for electron-download inside install.js
